### ISSUE TITLE
User Themes Gnome extension?

### ISSUE THREAD

**Issue by Thatoo** [Vanilla-OS/desktop-image#78] opened 2024-02-28 14:16 UTC
### Feature Description

User Themes is available as an extension in the Gome extensions manager right after a fresh install.
The choice is between 
- Default
- gnome-classic
- gnome-classic-high-contrast
only and I can't add more item to it. Adding theme to ~/.themes/gnome-shell doesn't work.
I didn't find a way to add themes to /usr/share/themes neither.

### Rationale

Be able to use an other theme in Vanilla OS than the default one.

**Comment by taukakao** [comment] 2024-02-28 23:05
I am not able to reproduce your issue. 
What theme are you trying to use?

**Comment by Thatoo** [comment] 2024-02-28 23:09
Where do you copy/paste your theme? 
I tried for example this one : https://www.pling.com/p/1214931

**Comment by taukakao** [comment] 2024-02-28 23:15
First, you usually have to extract them and then copy the theme folder inside into the .theme folder. 

So in the end you should have something like: `~/.themes/Flat-Remix-Blue-Dark/gnome-shell/assets`

**Comment by taukakao** [comment] 2024-02-28 23:16
Also, the theme that you linked is a GTK theme, not a shell theme

**Comment by Thatoo** [comment] 2024-02-28 23:20
my bad : https://www.pling.com/p/1013030

**Comment by taukakao** [comment] 2024-02-28 23:34
I'll close this. If the issue persists, just reopen it.

**Closed by taukakao** 2024-02-28 23:34 UTC
Labels: triage
