### ISSUE TITLE
Where can I find an offline installation package?

### ISSUE THREAD

**Issue by ZZH-Finalize** [Vanilla-OS/desktop-image#204] opened 2024-08-25 06:59 UTC
### Feature Description

I need to install Vanilla OS2 on a computer without internet access, but the official installation package eventually connects to GitHub to download data. How can I complete these actions in advance?

### Rationale

I need to install Vanilla OS2 on a computer without internet access, but the official installation package eventually connects to GitHub to download data. How can I complete these actions in advance?

**Comment by bohrium2b** [comment] 2024-09-06 06:43
As far as I know, there doesn't seem to be one yet. See https://github.com/Vanilla-OS/live-iso/issues/301.

**Comment by taukakao** [comment] 2024-11-08 13:51
Closing because it's a duplicate of https://github.com/Vanilla-OS/live-iso/issues/301

**Closed by taukakao** 2024-11-08 13:51 UTC
Labels: triage
